#!/usr/bin/env python3
"""Run op-img from a clone (`./op-img <patch> ...`), or symlink this file onto your PATH."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from op_img.cli import main  # noqa: E402

sys.exit(main())
